export const PixElementsMap = {
  btnTransfer: 'android=new UiSelector().description("Transferir")',
  inputSearchForUsers: 'android=new UiSelector().text("pesquisar usuários")',
  filteredUser: (description: string) => `android=new UiSelector().description("${description}")`,
  inputPixValue: 'android=new UiSelector().className("android.widget.EditText")',
  btnContinue: "accessibility id:CONTINUAR",
  btnConfirm: "accessibility id:CONFIRMAR",
  keyboardPIN: (digit: string) => `android=new UiSelector().description("${digit}")`,
  btnShowTransactionProof: "accessibility id:VER COMPROVANTE",
  btnAddKey: 'android=new UiSelector().description("")',
  txtKeyTypeByKeyType: (keyType: string) => `android=new UiSelector().text("${keyType}")`,
  btnCharge: 'android=new UiSelector().description("Cobrar")',
  btnCopyPaste: 'android=new UiSelector().description("Pix copia e cola")',
  btnPixKeyOptions: 'accessibility id:',
  btnDeletePixKey: 'accessibility id:, Apagar chave Pix, Delete a chave e abre espaço para a criação de outra em seu lugar',
};