name: Teste

on:
  workflow_dispatch:
   
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Test Selenium connectivity
        run: curl -s http://selenium:4444/status
