name: 🧪 Selenium Cucumber Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - name: Test Selenium connectivity
        run: curl -s http://selenium:4444/status
     
